# docker-compose for Jansky development.
#
# Note: Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: "2"
services:
  # This builds an image of the deploy base. Then we extend that with
  # dev-related things to do our dev-y stuff.
  deploy-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/jansky_deploy_base

  # This builds an image that extends Dockerfile with dev-related things.
  dev-base:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: local/jansky_dev

  # ------------------------------------------------------------------
  # After this point is dev-related services.
  # ------------------------------------------------------------------

  # Base container is used for development tasks like tests, linting, coverage
  # and building docs.
  base:
    image: local/jansky_dev
    environment:
      - COVERAGE_FILE=/tmp/.coverage
    volumes:
      - .:/app

  # Processor container for a prod-like Jansky.
  jansky:
    extends:
      service: base
    environment:
      - JANSKY_ENV=${JANSKY_ENV}
    command: ./bin/run_jansky.sh

  # https://hub.docker.com/r/kamon/grafana_graphite/
  # username: admin, password: admin
  statsd:
    image: kamon/grafana_graphite
    ports:
      - "9000:3000"  # grafana port
